name: Cypress Tests

on:
  schedule:
    - cron: "0 11 * * 1" # Toda segunda às 08h (horário Brasília)
  workflow_dispatch: # Permite rodar manualmente

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Instalar dependências
        run: npm install

      - name: Rodar Cypress (Cypress Cloud)
        uses: cypress-io/github-action@v6
        with:
          record: true
          start: "" # Não há app local → deixa vazio
          wait-on: "" # Como é URL externa, não precisa wait
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

